language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
 - chmod +x gradlew
 
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew test --debug"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ijak0190@gmail.com 